artifacts_root: artifacts
## where  running any components, it will generate an articats with the name of the component.
## for example, if running data_ingestion component, it will generate an
## artifacts with the name of data_ingestion.


## yaml file->  Key:Value
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1wJ1b6a1ApDuU4U7g1_tlu0zExuk1rUC8/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5




training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
